version: '2'

services:
  web:
    build: .
    ports:
      - 85:80
    volumes:
      - .:/var/www/html
    environment:
      - DB_DRIVER=pdo_mysql
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpass
      - DB_NAME=workshop
      - DB_PORT=3306
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=workshop
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 86:80